import copy
import unittest
import producer as p
import verifier as v

class Gates(unittest.TestCase):
 @classmethod
 def setUpClass(cls):
  cls.doc=p.produce(3)
 def reject(self,mutate):
  d=copy.deepcopy(self.doc);mutate(d)
  with self.assertRaises(ValueError):v.verify(d,3)
 def test_constructive_small_universe(self):
  self.assertEqual(v.verify(self.doc,3)['status'],'VERIFIED')
 def test_missing_graph(self):self.reject(lambda d:d['graphs'].pop())
 def test_duplicate_graph(self):self.reject(lambda d:d['graphs'].append(d['graphs'][0]))
 def test_same_count_substitution(self):self.reject(lambda d:d['graphs'].__setitem__(0,d['graphs'][1]))
 def test_wrong_q(self):self.reject(lambda d:d['graphs'][0]['q'][0].__setitem__(0,99))
 def test_missing_state(self):self.reject(lambda d:d['graphs'][-1]['states'].pop())
 def test_wrong_barrier(self):
  def f(d):next(g for g in d['graphs'] if g['pairs'])['pairs'][0]['primary'][0]+=1
  self.reject(f)
 def test_missing_pair(self):
  self.reject(lambda d:next(g for g in d['graphs'] if g['pairs'])['pairs'].pop())
 def test_duplicate_pair(self):
  def f(d):g=next(g for g in d['graphs'] if g['pairs']);g['pairs'].append(g['pairs'][0])
  self.reject(f)
 def test_illegal_path(self):
  def f(d):r=next(g for g in d['graphs'] if g['pairs'])['pairs'][0];r['paths'][0]=[r['paths'][0][0],r['paths'][0][-1]]
  self.reject(f)
 def test_wrong_verdict(self):self.reject(lambda d:d.__setitem__('outcome','UNIT_THEOREM'))
 def test_wrong_domain(self):self.reject(lambda d:d.__setitem__('bound',2))
 def test_valid_graph_order(self):
  d=copy.deepcopy(self.doc);d['graphs'].reverse();self.assertEqual(v.verify(d,3)['status'],'VERIFIED')
 def test_shape_enumerators(self):
  self.assertEqual(p.shapes(5),v.shapes(5));self.assertEqual(len(v.shapes(5)),17)
 def test_scalar_versus_lex_objective(self):
  # Costs generated by deviations (2,2,0) and (3,0,0): competing paths.
  A=[[1,2],[0,3],[0,3],[1,2]];C=[(0,0,0),(4,2,2),(3,3,1),(0,0,0)]
  primary,lex,paths,lp=p.barriers(A,C,0,3)
  self.assertEqual(primary,[3,2,1]);self.assertEqual(lex,[3,3,1])
 def test_lex_label_loss_control(self):
  A=[[1,2],[0,3],[0,3],[1,2,4],[3,5],[4]];C=[(0,0,0),(2,2,1),(3,1,3),(0,0,0),(3,1,3),(0,0,0)]
  self.assertEqual(p.barriers(A,C,0,5)[1],[3,1,3])
 def test_float_certificate_rejected(self):
  self.reject(lambda d:d['graphs'][0]['q'][0].__setitem__(0,0.0))
 def test_false_lower_threshold_cut(self):
  def f(d):
   r=next(g for g in d['graphs'] if g['pairs'])['pairs'][0];r['lower_reachable'][0].append(r['representatives'][1])
  self.reject(f)
 def test_false_endpoint_count(self):
  self.reject(lambda d:d['summary'].__setitem__('endpoint_pairs',0))
 def test_missing_required_field(self):
  self.reject(lambda d:d.pop('graphs'))
 def test_wrong_representative(self):
  self.reject(lambda d:next(g for g in d['graphs'] if g['pairs'])['pairs'][0].__setitem__('representatives',[0,0]))
 def test_pair_order_accepted(self):
  d=p.produce(4)
  for g in d['graphs']:g['pairs'].reverse()
  self.assertEqual(v.verify(d,4)['status'],'VERIFIED')
 def test_changed_historical_value_rejected(self):
  import run_campaign as c
  d=p.produce(3);checked=v.verify(d,3)
  key=checked['canonical_inherited_endpoint_pairs'][0];parents,k,q,a,b=key
  old={'pairs':[{'parents':parents,'view_count':k,'q':q,'a':[[i for i in range(len(parents)) if m>>i&1] for m in a],'b':[[i for i in range(len(parents)) if m>>i&1] for m in b],'B1':99,'Binf':1,'Bs':1}]}
  with self.assertRaises(ValueError):c.compare_historical(d,checked,old)
class Provenance(unittest.TestCase):
 def test_bound_provenance_accepts(self):
  import publication as z
  self.assertIsNone(z.validate_provenance({'id':7,'head_sha':'abc','run_attempt':2}, {'name':'v1637-science-abc','workflow_run':{'id':7,'head_sha':'abc'}}, {'head':'abc','trigger_sha':'abc','workflow_sha':'abc','run_id':'7','run_attempt':'2','phase':'science'},'abc','7','2'))
 def test_false_provenance_rejected(self):
  import publication as z
  base={'head':'abc','trigger_sha':'abc','workflow_sha':'abc','run_id':'7','run_attempt':'2','phase':'science'}
  for field in base:
   meta=dict(base);meta[field]='wrong'
   with self.subTest(field=field),self.assertRaises(ValueError):z.validate_provenance({'id':7,'head_sha':'abc','run_attempt':2},{'name':'v1637-science-abc','workflow_run':{'id':7,'head_sha':'abc'}},meta,'abc','7','2')
 def test_changed_and_omitted_source_rejected(self):
  import publication as z
  for actual in ({'a.py':'ok'},{'a.py':'ok','input.json':'changed'}):
   with self.assertRaises(ValueError):z.validate_source_map({'a.py':'ok','input.json':'right'},actual)
if __name__=='__main__':unittest.main(verbosity=2)
