def claim_ledger():
    return [
        {"name": "faithful finite PGRL source family", "status": "DERIVED", "boundary": "finite exact construction; lambda_source is not physical time"},
        {"name": "finite BKM/polar relational geometry", "status": "DERIVED", "boundary": "state-dependent tensors on a fixed abstract graph; not derived spacetime"},
        {"name": "SO(3) loop holonomy diagnostic", "status": "DERIVED", "boundary": "raw group holonomy angle only; not Riemann curvature or simplex deficit angle"},
        {"name": "QMAR source-response jet", "status": "DERIVED", "boundary": "first-order response conditional on full finite quantum state"},
        {"name": "response-selected current witness", "status": "CONDITIONAL", "boundary": "requires declared response aperture; weighted graph-current lift, not stress-energy"},
        {"name": "represented q=A^-1 DeWitt-like sign diagnostic", "status": "CONDITIONAL", "boundary": "quadratic-form sign structure only; no spatial-slice map, lapse, shift, constraints, or constraint algebra"},
        {"name": "controlled weak ADM/Einstein envelope", "status": "CONTROLLED_CORRESPONDENCE", "boundary": "historical external analytical comparison only; never a selector and not generated by this demo"},
        {"name": "RGCL source-to-coframe coupling magnitude", "status": "MISSING_LAW", "boundary": "projective Sigma ray does not fix magnitude; a free dimensionful scale would be added calibration, not derivation"},
        {"name": "toy block-underdetermination control", "status": "CONTROL", "boundary": "two hand-declared 3x3 blocks share the declared lower-order projection but differ; not a derived T_munu decomposition"},
        {"name": "ontology-native continuum refinement / QRSL", "status": "MISSING_LAW", "boundary": "QRSL irreducible relative to frozen ontology"},
        {"name": "physical Einstein closure", "status": "MISSING_LAW", "boundary": "not derived"},
    ]
